### ISSUE TITLE
Thank you 🤗 and link to a similar tool

### ISSUE THREAD

**Issue by piotr-yuxuan** [KingMob/TrueGrit#1]
Hello, thank you for this great little project! I wonder if you've come across safely [0] and whether you could find there ideas to port to TrueGrit? :-)

[0] https://github.com/BrunoBonacci/safely

**Comment by KingMob** [comment]
Thanks @piotr-yuxuan! 

I wrote the initial impl of True Grit ~3 years ago, and I don't recall seeing `safely` at the time, though it would have been around. I just remember not liking the alternatives I did find, but we had to do something because Netflix was sunsetting Hystrix, so I wrote my own. I love Bonacci's mulog library and its ideas, however, so I'm open to suggestions. What do you want to see?

I looked over `safely` for ideas, and if you're currently using it, I can see a few things you might want to be aware of:
- One issue I see is only supporting 1s buckets for the circuit breaker. Fixed time windows don't work well with both very fast (can be slow to respond to obvious failure) and very slow (may not have enough calls in buckets to analyze) relative calling rates, which is part of _why_ Hystrix was sunsetted by Netflix, and why Resilience4j CBs default to counting the last _N_ calls, regardless of time windows.
- It looks like `safely` CB state is keyed off more than a name/keyword, which is mildly suboptimal, because it means you can't share a circuit breaker across multiple fns. This is useful when you have multiple fns hitting the same underlying service (e.g., if fns `get-flaky-service` and `put-flaky-service` want to share what they both know about trying to use "flaky-service")
- Forces CB calls to use a separate thread pool, even if you're handling threads higher up/lower down/don't want to. I think this is mixing concerns, and would rather have separate bulkheads. (Minor bug, the `safely` macro doesn't default to `bound-fn` or any other thread frame copying method, which will cause surprise problems with fns like `binding` (though people should really avoid thread-specific binding anyway)). 

OTOH `safely` does some things I wish True Grit did:
- It enforces a general good ordering, so you can't accidentally apply resilience policies in the wrong order. I had a fn like that, but I simplified it and moved it to a comment (called `robustify`) because the original syntax was kind of awkward. But I do worry about people shooting themselves in the foot.
- No Java leakage. I tried to minimize it, but there are definitely a few places here and there, mostly in typed exceptions and retry interval-calculating fns, where r4j leaks out
- Fewer options. For both good and bad, r4j, and thus True Grit, have a _lot_ of options.

That being said, I think True Grit is more composable, extensive, and simpler, but hey, I'm biased. 😄

**Comment by KingMob** [comment]
Hmmm, I just thought of a slight addendum in regards to saying "It looks like `safely` CB state is keyed off more than a name/keyword". Since it keys off all the options, you should be able to share the same CB between multiple fns if all the options are the same, including the CB name. _But_, that means they all have to have the same retry/timeout/etc policy, which you may not want to share.

Anyway, @piotr-yuxuan did you see my Slack messages about primitive-math and byte-streams PRs?
